INHERIT: active-handout.yml

site_name: MLOps & Interviews

extra:
  custom_variables:
    repo_aps: https://github.com/insper/mlops
    repo_aps_git: https://github.com/insper/mlops.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css

nav:
  - 'Home': index.md
  - about.md
  - deadlines.md
  - contributions.md
  - Classes:
    - "01 - Introduction":
      - classes/01-intro/intro.md
      - classes/01-intro/aps01_part_1.md
      - classes/01-intro/aps01_part_2.md
    - "02 - Deploy: first try!":
      - classes/02-api/api_deploy.md
    - "03 - Batch prediction":
      - "Part 1":
        - classes/03-batch/intro.md
        - classes/03-batch/data_formats.md
        - classes/03-batch/practicing.md
      # - "Part 2":
      #   - classes/03-batch/sql.md
      #   - classes/03-batch/db_tool.md
      #   - classes/03-batch/dot_env.md
      #   - classes/03-batch/aps02_sql.md